name: Google Cloud Function Deployment
on:
  push:
    branches:
      - main
jobs:
    Deploy:
      name: Deploy
      runs-on: ubuntu-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: GCP Authentication
        id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - name: Debug GCP credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > credentials.json
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: 'Buat zip dari sumber kode'
        run: 'zip -r function.zip *'
      - name: 'Deploy a gen 2 cloud function'
        run: 'gcloud functions deploy wamyid --region=asia-southeast1 --allow-unauthenticated --entry-point=WebHook --gen2 --runtime=go122 --trigger-http --verbosity=debug --source=./function.zip --set-env-vars=[MONGOSTRING=${{ secrets.MONGOSTRING }},WAPHONENUMBER=${{ secrets.WAPHONENUMBER }}]'
      - name: 'Cek eksistensi fungsi'
        run: 'gcloud functions describe wamyid --region=asia-southeast1'
      - name: 'Cek log debugging'
        run: 'gcloud functions logs read wamyid --region=asia-southeast1'
      # - name: 'Cleaning Artifact Registry'
      #   run: 'gcloud artifacts repositories delete gcf-artifacts --location=asia-southeast1 --quiet'